// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yxymnshvmeblkbuvrqmv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl4eW1uc2h2bWVibGtidXZycW12Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAxMDk4NDEsImV4cCI6MjA1NTY4NTg0MX0.8uBpKn3seWx9GdNu62Q6lVZiUENG6EVFPwV0TW6IHAg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});